# Generated by Django 2.2.3 on 2019-07-15 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190714_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='events', through='events.EventUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
